name: CI/CD Pipeline
on: 
    pull_request:
        branches:
            - main

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/setup-node@v4
            
            -   name: Set up Node.js
                uses: actions/setup-node@v4
                with:
                    'node-version': '20'

            -   name: Install dependencies
                run: npm install
                working-directory: .  

            -   name: Liting e Tipagem
                run: npm run lint

            -   name: Testes
                run: npm run test

            -   name: Build
                run: npm run build
            
            -   name: Print mensagem final
                run: echo Execução de pipeline concluída com sucesso!


            

